### ISSUE TITLE
Forced creation of cache location

### ISSUE THREAD

**Issue by dougmitarotonda** [HenrikBengtsson/R.cache#16]
On package startup, there is no way to either default to "Y" or "n" to the question posed about the default cache location. This is particularly frustrating in that I'd actually prefer to use `setCacheRootPath` immediately to use my own defined cache location. However, that does not persist across sessions so I'm always asked the startup question. The easiest solution I've come up with is just to press Y on the first startup and then `setCacheRootPath` immediately so that I have a "~/.Rcache" folder that is empty and that I never use. I hate having that sort of clutter and it is potentially confusing to my users. 

The easiest fix for this would be to have a way to default to "n" on startup so that a temp folder is created (and later deleted) while my more permanent cache could be used, without polluting my ~ folder.

**Comment by HenrikBengtsson** [comment]
Thank you for the constructive feedback.

First, the rationale for setting up the cache root directory when the package is loaded so that the user get's prompted as early as possible, which ideally happens when the user loads/attaches another package which imports the R.cache package.   The alternative would be to set up the cache directory the first time the cache is needed (read or saved).  However, if that happens hours into a long running job, then the job will stall until the user answers the prompt.  Thus, it was deliberately choose to occur as soon as ever possible (= R.cache is loaded).  BTW, if you don't know, the reason for having a prompt, is due to the [CRAN Policies](https://cran.r-project.org/web/packages/policies.html) requiring users explicit permission to write to disk (other than `tempdir()`).

There is actually a [hidden option in R.cache](https://github.com/HenrikBengtsson/R.cache/blob/master/R/getCacheRootPath.R#L38) that allows you to do what you want.  For example,
```r
> options("R.cache::rootPath"="~/foo/bar")
> R.cache::getCacheRootPath()
[1] "~/foo/bar/"
```
This should circumvent any prompts.

Hope this helps

PS. The main reason the option is undocumented is that I went back and forth on how the option should named and whether a system environment variable or not should be supported.

**Comment by dougmitarotonda** [comment]
Perfect! I threw that line into my .Rprofile and things work exactly as you described. 

While I don't profess to understand all of the CRAN nuances you have to deal with in a package like this, I do appreciate the challenges you described. 

The only suggestion I have now is to make this a documented feature. I'll leave this ticket open and leave it up to you as to whether or not you want to do it or just close the ticket. 

Thanks again - and well done on the package, it works great!

**Comment by HenrikBengtsson** [comment]
R.cache 0.13.0 is now on CRAN.  It has an option `R.cache.enabled` making it possible to disable cache loading/saving.  See `?R.cache.options`.

**Comment by HenrikBengtsson** [comment]
Woops, commented to the wrong issue.  The comment here should be:

R.cache 0.13.0 is now on CRAN. This is now documented/clarified in `?R.cache.options`.
