### ISSUE TITLE
support for parallel processing of overlapping tasks

### ISSUE THREAD

**Issue by gezakiss7** [HenrikBengtsson/R.cache#7]
This is probably not a critical issue, but might be an enhancement.

Problem: You run multiple tasks parallelly, and some subtasks that you want to cache are part of multiple tasks. Currently each task would compute and save the result. (Not sure if this can cause a problem if they try to write the same file simultaneously.)

Vision: Each subtask is computed only once, and the other parallel processes just wait for and read the results.

A possible strategy: The first process that goes about performing a subtask indicates that for the others processes; those just sleep until it is finished, and then load and return the cached result. 
(If the first process fails, it indicates failure upon exit, or if it crashes, the processes just wait indefinitely until terminated.)

Regarding implementation, the synchronicity package may be suitable; or simply creating a directory for the cache file name, and proceeding only once it succeeds, and removing it afterwards.

**Comment by HenrikBengtsson** [comment]
Just to make it clear: R.cache is robust against errors in this sense. If there's a race condition such that one process overwrites an existing cache file that another process is currently reading such that the latter fails to read the cached data, it will silently ignore the cache file.  In other words, it will behave as the cached file was never there.  This means that the risk for reading in partial/corrupt cache data is zero.

For your vision:  Synchronization via file systems is problematic and very hard to get working across file systems and operating systems, e.g. https://groups.google.com/forum/#!searchin/batchjobs/from$3Ame/batchjobs/15IIm_Nb4YQ/iwiGFYIPpmwJ and https://github.com/tudo-r/BatchJobs/issues/50.  Don't get me wrong, I'd probably be the first one using a library/R package that would provide a bullet-proof solution for this, but it just doesn't exist.

One could take an optimistic approach with R.cache, because no damage is made if the value has to be recalculated.  One approach would be to create a temporary `<cache>.lock` file and have other processes wait for this lock file to go away, i.e. basically pool, wait, pool, wait, ...  The problem with pooling is - for how long should one wait until giving up?  Maybe that other process was aborted for unknown reasons and the `<cache>.lock` file is simply a stray file that will never disappear.  Then, "who" (which process) is responsible for cleaning up such failed cache files?

So, the question is, is this feature really useful and if so, is this something that R.cache should do or should such synchronization be done a level up?  I'd argue that memoization/caching is a separate problem/task than synchronization.

**Comment by HenrikBengtsson** [comment]
Closing this one.

**Comment by gezakiss7** [comment]
Thanks for the explanation. Yes, it makes sense.
